import PDFDocument from "pdfkit";
import type { InvoiceLineRow, InvoiceRow } from "./invoices.repository";

/**
 * The framework-default invoice PDF. Self-contained: pdfkit plus the standard
 * Helvetica core fonts, so no wkhtmltopdf, no headless Chrome and no font
 * licensing. The visible content mirrors the reference renderer section for
 * section (`billing/invoice_pdf.py`); the byte layout is the engine's own.
 */

// A4 portrait in PostScript points (pdfkit's unit), 18mm margins like the reference.
export const PAGE_WIDTH = 595.28;
const MARGIN = 51;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

const INK = "#18181b"; // zinc-900
const MUTED = "#71717a"; // zinc-500
const HAIRLINE = "#e4e4e7"; // zinc-200
const TABLE_HEAD_FILL = "#f4f4f5";

const SYMBOLS: Record<string, string> = { PHP: "PHP ", USD: "USD ", EUR: "EUR " };

export interface InvoicePdfInput {
  readonly invoice: InvoiceRow;
  readonly lines: readonly InvoiceLineRow[];
  readonly orgName: string;
  readonly billingEmail?: string | null;
  readonly payToInstructions?: string | null;
}

export function formatMoney(cents: number, currency: string): string {
  const symbol = SYMBOLS[currency] ?? `${currency} `;
  return `${symbol}${(cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function formatQuantity(quantity: number): string {
  return quantity.toLocaleString("en-US");
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/** `Sep 29, 2026` in UTC — invoices are dated by the period they bill, not the reader's clock. */
export function formatDate(value: Date): string {
  return `${MONTHS[value.getUTCMonth()] as string} ${String(value.getUTCDate()).padStart(2, "0")}, ${String(value.getUTCFullYear())}`;
}

/** Render the invoice and resolve with the complete PDF bytes. */
export function renderInvoicePdf(input: InvoicePdfInput): Promise<Buffer> {
  const { invoice } = input;
  const number = invoice.number ?? invoice.id;
  const doc = new PDFDocument({ size: "A4", margin: MARGIN, info: { Title: `Invoice ${number}` } });
  const chunks: Buffer[] = [];
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  header(doc, invoice, number);
  billTo(doc, input.orgName, input.billingEmail ?? null);
  meta(doc, invoice);
  table(doc, input.lines, invoice.currency);
  totals(doc, invoice);
  instructions(doc, invoice, input.payToInstructions ?? null);
  footer(doc, number);
  doc.end();
  return done;
}

function header(doc: PDFKit.PDFDocument, invoice: InvoiceRow, _number: string): void {
  doc.font("Helvetica-Bold").fontSize(18).fillColor(INK).text("Synapse", MARGIN, MARGIN);
  doc.font("Helvetica").fontSize(9).fillColor(MUTED).text("Generated by the Synapse SaaS Framework");
  doc.moveDown(1);
  doc.font("Helvetica-Bold").fontSize(14).fillColor(INK).text(`INVOICE ${invoice.number ?? ""}`, MARGIN, doc.y, { width: CONTENT_WIDTH, align: "right" });
  const rule = doc.y + 6;
  doc.lineWidth(1).strokeColor(HAIRLINE).moveTo(MARGIN, rule).lineTo(PAGE_WIDTH - MARGIN, rule).stroke();
  doc.y = rule + 16;
}

function billTo(doc: PDFKit.PDFDocument, orgName: string, billingEmail: string | null): void {
  const top = doc.y;
  doc.font("Helvetica").fontSize(9).fillColor(MUTED).text("Billed to", MARGIN, top, { width: 85, continued: false });
  doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(orgName, MARGIN + 85, top, { width: CONTENT_WIDTH - 85 });
  if (billingEmail) doc.font("Helvetica").fontSize(9).fillColor(MUTED).text(billingEmail, MARGIN + 85, doc.y, { width: CONTENT_WIDTH - 85 });
  doc.y += 12;
}

function meta(doc: PDFKit.PDFDocument, invoice: InvoiceRow): void {
  const pairs: [string, string][] = [];
  if (invoice.period_start !== null && invoice.period_end !== null) {
    pairs.push(["Period", `${formatDate(invoice.period_start)} - ${formatDate(invoice.period_end)}`]);
  }
  if (invoice.issued_at !== null) pairs.push(["Issued", formatDate(invoice.issued_at)]);
  pairs.push(["Status", invoice.status.toUpperCase()]);

  const columnWidth = CONTENT_WIDTH / pairs.length;
  const labelRow = doc.y;
  doc.font("Helvetica").fontSize(9).fillColor(MUTED);
  pairs.forEach(([label], index) => {
    doc.text(label, MARGIN + index * columnWidth, labelRow, { width: columnWidth });
  });
  const valueRow = labelRow + 14;
  doc.fillColor(INK);
  pairs.forEach(([, value], index) => {
    doc.text(value, MARGIN + index * columnWidth, valueRow, { width: columnWidth });
  });
  doc.y = valueRow + 28;
}

const COLUMNS = [222, 68, 102, 102] as const; // description, qty, unit price, amount

function table(doc: PDFKit.PDFDocument, lines: readonly InvoiceLineRow[], currency: string): void {
  const headings = ["Description", "Qty", "Unit price", "Amount"] as const;
  let y = doc.y;
  const headerHeight = 22;
  doc.rect(MARGIN, y, CONTENT_WIDTH, headerHeight).fillAndStroke(TABLE_HEAD_FILL, HAIRLINE);
  doc.font("Helvetica-Bold").fontSize(9).fillColor(MUTED);
  let x = MARGIN;
  headings.forEach((label, index) => {
    doc.text(label, x + 4, y + 7, { width: (COLUMNS[index] as number) - 8 });
    x += COLUMNS[index] as number;
  });
  y += headerHeight;

  doc.font("Helvetica").fontSize(9).fillColor(INK);
  if (lines.length === 0) {
    doc.rect(MARGIN, y, CONTENT_WIDTH, 22).stroke(HAIRLINE);
    doc.fillColor(INK).text("No billable items this period", MARGIN + 4, y + 7, { width: CONTENT_WIDTH - 8 });
    doc.y = y + 22;
    return;
  }

  for (const line of lines) {
    const rowHeight = line.metric === null ? 26 : 34;
    doc.rect(MARGIN, y, CONTENT_WIDTH, rowHeight).stroke(HAIRLINE);
    const cells = [line.description, formatQuantity(line.quantity), formatMoney(line.unit_amount_cents, currency), formatMoney(line.amount_cents, currency)];
    x = MARGIN;
    cells.forEach((value, index) => {
      doc.font("Helvetica").fontSize(9).fillColor(INK).text(value, x + 4, y + 6, { width: (COLUMNS[index] as number) - 8, ellipsis: true, height: 12 });
      x += COLUMNS[index] as number;
    });
    if (line.metric !== null) {
      doc.font("Helvetica-Oblique").fontSize(7).fillColor(MUTED).text(line.metric, MARGIN + 4, y + rowHeight - 12, { width: (COLUMNS[0] as number) - 8 });
    }
    y += rowHeight;
  }
  doc.y = y;
}

function totals(doc: PDFKit.PDFDocument, invoice: InvoiceRow): void {
  const left = PAGE_WIDTH - MARGIN - 255;
  const labelWidth = 142;
  const valueWidth = 113;
  let y = doc.y + 12;
  const row = (label: string, value: string, bold: boolean): void => {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(bold ? 11 : 9);
    doc.fillColor(bold ? INK : MUTED).text(label, left, y, { width: labelWidth });
    doc.fillColor(INK).text(value, left + labelWidth, y, { width: valueWidth, align: "right" });
    y += bold ? 20 : 17;
  };
  row("Subtotal", formatMoney(invoice.subtotal_cents, invoice.currency), false);
  row("Tax", formatMoney(invoice.tax_cents, invoice.currency), false);
  doc.lineWidth(1).strokeColor(INK).moveTo(left, y).lineTo(PAGE_WIDTH - MARGIN, y).stroke();
  y += 6;
  row("Total due", formatMoney(invoice.total_cents, invoice.currency), true);
  doc.y = y + 8;
}

function instructions(doc: PDFKit.PDFDocument, invoice: InvoiceRow, payTo: string | null): void {
  if (invoice.status === "paid") {
    const when = invoice.paid_at === null ? "" : ` - ${formatDate(invoice.paid_at)}`;
    doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(`PAID${when}`, MARGIN, doc.y, { width: CONTENT_WIDTH });
    return;
  }
  if (!payTo) return;
  doc.font("Helvetica-Bold").fontSize(9).fillColor(MUTED).text("Payment instructions", MARGIN, doc.y, { width: CONTENT_WIDTH });
  doc.font("Helvetica").fontSize(9).fillColor(INK).text(payTo, MARGIN, doc.y, { width: CONTENT_WIDTH });
}

function footer(doc: PDFKit.PDFDocument, number: string): void {
  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(range.start + index);
    doc
      .font("Helvetica-Oblique")
      .fontSize(8)
      .fillColor(MUTED)
      .text(`Invoice ${number} - page ${String(index + 1)}/${String(range.count)}`, MARGIN, 812 - 24, { width: CONTENT_WIDTH, align: "center" });
  }
}
